### ISSUE TITLE
Trouble visualising .txt imports 

### ISSUE THREAD

**Issue by Powellrm** [tchitchek-lab/CytoCompare#2]
Currently trying to plot from imported .txt files. I'm able to plot everything via plot(imported.clusters) however as soon as I specify for example plot(imported.clusters[1]) i get an error : Error in x@densities[k, l, drop = FALSE] : subscript out of bounds
I understand that .txt file do not contain density information, however would this affect being able to visualise individual clusters this way?

**Comment by nicolas-tchitchek** [comment]
Indeed, you are right.
We have corrected this point to allow the display of cluster phenotypes loaded without the densities. Please update the R package.
